name: portfolio
description: Portfolio website project
publish_to: 'none'
version: 1.0.9+1
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  get:
  shared_preferences:
  google_fonts:
  floating_bubbles: ^2.5.1
  restart_app:
  url_launcher:
  animated_text_kit:
  font_awesome_flutter:
  lottie:
  firebase_core:
  flutter_animate: ^4.2.0+1
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - lib/assets/